apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    app: calico-ipip-pinger
  name: calico-ipip-pinger
  namespace: kube-system
spec:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: calico-ipip-pinger
    spec:
      serviceAccountName: calico-ipip-pinger
      containers:
      - name: calico-ipip-pinger
        image: quay.io/giantswarm/calico-ipip-pinger:latest
        imagePullPolicy: Always
        securityContext:
          privileged: true
        env:
          # The location of the Calico etcd cluster.
          - name: ETCD_ENDPOINTS
            valueFrom:
              configMapKeyRef:
                name: calico-config
                key: etcd_endpoints
          # Location of the CA certificate for etcd.
          - name: ETCD_CA_CERT_FILE
            valueFrom:
              configMapKeyRef:
                name: calico-config
                key: etcd_ca
          # Location of the client key for etcd.
          - name: ETCD_KEY_FILE
            valueFrom:
              configMapKeyRef:
                name: calico-config
                key: etcd_key
          # Location of the client certificate for etcd.
          - name: ETCD_CERT_FILE
            valueFrom:
              configMapKeyRef:
                name: calico-config
                key: etcd_cert
        volumeMounts:
          # Mount in the etcd TLS secrets.
          - mountPath: /etc/kubernetes/ssl/etcd
            name: etcd-certs
      volumes:
        # Mount in the etcd TLS secrets.
        - name: etcd-certs
          hostPath:
            path: /etc/kubernetes/ssl/etcd
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
      hostNetwork: true
      restartPolicy: Always
