---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: calico-ipip-pinger-psp
subjects:
- kind: ServiceAccount
  name: calico-ipip-pinger
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: privileged-psp-user
  apiGroup: rbac.authorization.k8s.io
